language: swift

osx_image: 
- xcode10.2

env:
- SCHEME=Keikai SWIFT_VERSION=5.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

xcode_project: Keikai.xcodeproj

xcode_scheme: Keikai

script:
  - bundle exec fastlane test_ci