# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

def shared_pods
    pod 'Keikai', git: 'https://github.com/aashishtamsya/Keikai', tag: '0.0.1'
end

target 'KeikaiExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeikaiExample
	shared_pods
	
  target 'KeikaiExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
